#!/bin/sh
#
# Plugin to measure uptime of an ejabberd-node using ejabberdctl.
# This is more or less based on the uptime-plugin shipping with munin.
#
# Contributed by Mathias Ertl <mati@fsinf.at>
#
# $Log$
# Revision 1.0  2008/12/22 17:58:39  mati
# Added inital version
#
#
# Magic markers
#
#%# family=auto
#%# capabilities=autoconf

if [ "$1" = "autoconf" ]; then
	which ejabberdctl > /dev/null
	if [ $? -eq 0 ]; then
		echo yes 
		exit 0
	else
		echo 'no (ejabberdctl not found)'
		exit 1
	fi
fi

if [ "$1" = "config" ]; then
	echo 'graph_title ejabberd uptime
graph_args --base 1000 -l 0 
graph_vlabel uptime in days
uptime.label uptime
uptime.draw AREA
graph_category ejabberd'
	exit 0
fi

uptime=$(ejabberdctl stats uptimeseconds)
value=$(echo $uptime'/86400' | bc -l)
alignedValue=$( printf '%.4f' $value )
echo uptime.value $alignedValue
