#!/bin/bash
#
# Plugin to measure the number of users that were online in a given number of
# days.
#
# This is a wildcard plugin. To monitor the last seven days, link
# ejabberd_active_users_<days> to this file, e.g.:
# 
#   ln -s /usr/share/munin/plugins/ejabberd_active_users_ \
#         /etc/munin/plugins/ejabberd_active_users_7
#
# Configuration:
#
# [ejabberd_active_users_*]
# user ejabberd
# group ejabberd
# # optional, otherwise all vhosts are used:
# #env.hosts jabber.at jabber.wien jabber.zone
#
# Contributed by Mathias Ertl <mati@jabber.at>
#
# $Log$
# Revision 1.0  2014/11/01 18:03:22  Mathias Ertl
# Added inital version
#
# Magic markers
#
#%# family=auto
#%# capabilities=autoconf suggest

if [ "$1" = "autoconf" ]; then
    which ejabberdctl > /dev/null
    if [ $? -eq 0 ]; then
        echo yes
        exit 0
    else   
        echo 'no (ejabberdctl not found)'
        exit 1
    fi
elif [ "$1" = "suggest" ]; then
    echo 7
    echo 31
    exit 0
fi

days=${0##*/ejabberd_active_users_}
if [ -z "$hosts" ]; then
    hosts=$(ejabberdctl registered_vhosts)
fi

clean_name() {
    echo $1 | sed 's/[\/.-]/_/g'
}


if [ "$1" = "config" ]; then
    echo "graph_title Number of active users in the last $days days
graph_args --base 1000 -l 0
graph_vlabel users
graph_scale no
graph_category ejabberd"

    for host in $hosts; do
        label=`clean_name $host`
        echo $label.label $host
        echo $label.info Number of active users on $host in the last $days days
    done
    exit 0
fi

for host in $hosts; do
    label=`clean_name $host`
    echo $label.value $(ejabberdctl num_active_users $host $days)
done
