#!/bin/sh

#
# This script dumps all mysql databases compressed into /var/backups/mysql/
#

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

TARGET=/var/backups/mysql
IGNORE="information_schema|performance_schema"
CONF=/etc/mysql/debian.cnf
TIMESTAMP=$(date +"%Y-%m-%d")
BACKUP_DIR="$TARGET/$TIMESTAMP"

# Delete backups older than 10 days
find $TARGET/ -type f -mtime +10 -delete
find $TARGET/ -type d -empty -delete



if [ ! -r $CONF ]; then
	logger "$0 - auf $CONF konnte nicht zugegriffen werden";
	echo "$0 - auf $CONF konnte nicht zugegriffen werden"
	exit 1;
fi

mkdir -p $BACKUP_DIR

if [ ! -d $BACKUP_DIR ] || [ ! -w $BACKUP_DIR ]; then
	logger "$0 - Backup-Verzeichnis nicht beschreibbar";
	echo "$0 - Backup-Verzeichnis nicht beschreibbar";
	exit 1;
fi

DBS="$(/usr/bin/mysql --defaults-extra-file=$CONF -Bse 'show databases' | /bin/grep -Ev $IGNORE)"

for DB in $DBS; do
	if [ ! "$DB" == "ejabberd" ]; then
		/usr/bin/mysqldump --defaults-extra-file=$CONF --comments --dump-date --events --lock-tables $DB > $BACKUP_DIR/$DB.sql
	fi
done

logger "$0 - Backup $TIMESTAMP erfolgreich durchgefuehrt"

exit 0
